FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["Covid19Api.csproj", "./"]
RUN dotnet restore "./Covid19Api.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Covid19Api.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Covid19Api.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Covid19Api.dll"]
